# Generated by Django 4.1.2 on 2022-11-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gift", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="gift",
            name="title",
            field=models.CharField(default="", max_length=64),
        ),
    ]
