# Generated by Django 4.1.2 on 2022-11-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gift", "0002_gift_content_gift_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gift",
            old_name="title",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="gift",
            name="content",
        ),
        migrations.AddField(
            model_name="gift",
            name="img",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="gift",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gift",
            name="url",
            field=models.CharField(default="", max_length=128),
        ),
    ]
