# Generated by Django 4.1.2 on 2022-11-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gift", "0003_rename_title_gift_name_remove_gift_content_gift_img_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gift",
            name="url",
        ),
        migrations.AddField(
            model_name="gift",
            name="link",
            field=models.URLField(default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="gift",
            name="img",
            field=models.URLField(default="", max_length=400),
        ),
    ]
