dist: bionic

jobs:
  include:
    - language: python
      python: "3.9"
      install:
        - cd backend
        - pip install -r requirements.txt
      script:
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml

    - language: node_js
      node_js: "14"
      install:
        - cd frontend
        - npm install
      script:
        - ./node_modules/.bin/eslint src
        - npm run test -- --coverage --watchAll=false