on:
  push:
    branches:
    - main
    - 'sprint**'
  pull_request:
    branches:
    - main

name: Run Tests

jobs:

  backend-test:
    name: Backend Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4

    - name: Install Requirements
      run: pip install -r requirements.txt

    - name: Run Tests
      run: coverage run manage.py test

    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
        flag-name: Backend
        debug: true


  frontend-test:
    name: Frontend Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: npm install
      run: |
        npm install
        npm run test -- --coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true
        path-to-lcov: ./frontend/coverage/lcov.info
        flag-name: Frontend

  coveralls_finish:
    needs: [frontend-test, backend-test]
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
